# Generated by Django 3.1.4 on 2021-02-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='date',
        ),
    ]
